/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formPrintOut.java
 *
 * Created on 04 Agu 11, 12:20:25
 */

package overtimeapplication;

/**
 *
 * @author arip
 */
//import java.io.File;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import java.sql.*;
import java.sql.Connection;
import java.awt.event.*;
//import javax.swing.text.*;
//import java.util.*;
//import java.io.FileInputStream;
//import java.io.FileNotFoundException;
//import java.util.ArrayList;
import java.util.HashMap;
//import java.util.List;
import java.util.Map;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import net.sf.jasperreports.engine.JREmptyDataSource;
//import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
//import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

public class formPrintPegawai extends javax.swing.JFrame {
    DefaultTableModel tabMode;
    Connection con;
    String xpanggil;
    public formPrintPegawai(String panggil) {
        initComponents();
        xpanggil=panggil;
        Object[] row = {"Nip","Nama"};
        tabMode = new DefaultTableModel(null,row);
        tblPrint.setModel(tabMode);

        tblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(MouseEvent e){
            dapatData_dari_Tabel();
            }
        });
        koneksiDatabase();
        tampilDatakeTabel();
    }

    /** Creates new form formPrintOut */
    public formPrintPegawai() {
        this.setLocation(500, 225);
        setResizable(false);
        initComponents();

        Object[] row = {"Nip","Nama"};
        tabMode = new DefaultTableModel(null,row);
        tblPrint.setModel(tabMode);

        tblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(MouseEvent e){
                dapatData_dari_Tabel();
            }
        });
        koneksiDatabase();
        tampilDatakeTabel();
    }

public void koneksiDatabase()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("sukses Driver JDBC ditemukan....");
            try {
                String url = "jdbc:mysql://localhost:3306/payroll_db?user=root&password=admin";
                con = DriverManager.getConnection(url);
                System.out.println("Sukses Koneksi ...");
            }
            catch (SQLException se) {
            System.out.println("Koneksi Gagal ... "+se);
            System.exit(0);
            }
        }
    catch (ClassNotFoundException cnfe) {
    System.out.println("Class tidak ditemukan... Error : "+cnfe);
    System.exit(0);
    }
    }
public void tampilDatakeTabel() {
     hapusTabel();
     try{
         String sql = "Select * from pegawai";
         Statement stat = con.createStatement();
         ResultSet set = stat.executeQuery(sql);
         while (set.next()) {
             String nim = set.getString("nip");
             String nama = set.getString("nama");
             String[] data = {nim,nama};
             tabMode.addRow(data);
         }
     }
     catch (Exception e){}
 }
public void hapusTabel(){
        int row = tabMode.getRowCount();
        for (int i = 0; i<row; i++) {
            tabMode.removeRow(0);
        }
    }
void dapatData_dari_Tabel()
 {
     int row=tblPrint.getSelectedRow();
     String nip= tabMode.getValueAt(row,0).toString();
     txtNip.setText(nip);
     txtNip.requestFocus();
     }
public void proses_cariData(String sql) {
    hapusTabel();
    try{
        Statement stat = con.createStatement();
        ResultSet set = stat.executeQuery(sql);
        while (set.next()){
        String nip = set.getString("nip");
        String nama = set.getString("nama");
        String[] data = {nip,nama};
        tabMode.addRow(data);
    }
        stat.close();
}
    catch (Exception e) {}
}
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnPrintAll = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        btnPrintSingle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrint = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Print Pegawai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrintAll.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnPrintAll.setText("Print All");
        btnPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnCari.setText("Search");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtClear.setFont(new java.awt.Font("Times New Roman", 0, 14));
        txtClear.setText("Clear");
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel2.setText("Nama       :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel3.setText("NIP          :");

        btnPrintSingle.setFont(new java.awt.Font("Times New Roman", 0, 14));
        btnPrintSingle.setText("Print");
        btnPrintSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintSingleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtNip)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrintAll)
                        .addGap(18, 18, 18)
                        .addComponent(txtClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPrintSingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrintSingle))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(txtClear)
                    .addComponent(btnPrintAll))
                .addContainerGap())
        );

        tblPrint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrintMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllActionPerformed
        // TODO add your handling code here:
        proses_cariData("select * from pegawai");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/payroll_db?user=root&password=admin";
            con=DriverManager.getConnection(url);
            System.out.println("Sukses koneksi");

            Map myVar = new HashMap();

            JasperReport myReport=JasperCompileManager.compileReport("D://New Project/iReport/Data Pegawai.jrxml");
            JasperPrint myPrint=JasperFillManager.fillReport(myReport,myVar,con);
            JasperViewer.viewReport(myPrint,false);
            dispose();
        }
        catch(Exception e){}
    }//GEN-LAST:event_btnPrintAllActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    String nip="";
    nip=txtNip.getText();
    String url = "jdbc:mysql://localhost:3306/payroll_db";
    String Driver = "com.mysql.jdbc.Driver";
    String user = "root";
    String pass = "admin";
    try{
        Class.forName(Driver);
        Connection konek=DriverManager.getConnection(url,user,pass);
        Statement st=konek.createStatement();
        String sql="select * from pegawai where nip='"+nip+"'";
        ResultSet rs=st.executeQuery(sql);
        if (rs.next()){
            txtNip.setText(rs.getString(1));
            txtNama.setText(rs.getString(2));
            proses_cariData(sql);
        }else{
        JOptionPane.showMessageDialog(null,"Maaf, NIP "+nip+"\nTidak Ditemukan");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Maaf.... Ada Kesalahan\n"+e.getMessage());
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrintMouseClicked
        // TODO add your handling code here:
        //dapatData_dari_Tabel();
        txtNip.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 0).toString());
        txtNama.setText(tblPrint.getValueAt(tblPrint.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tblPrintMouseClicked

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        // TODO add your handling code here:
        txtNip.setText("");
        txtNama.setText("");
        txtNip.requestFocus();
    }//GEN-LAST:event_txtClearActionPerformed

    private void btnPrintSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintSingleActionPerformed
        // TODO add your handling code here:
        proses_cariData("select * from pegawai");
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/payroll_db?user=root&password=admin";
            con=DriverManager.getConnection(url);
            System.out.println("Sukses koneksi");

            HashMap hm=new HashMap();
            hm.put("NIP",txtNip.getText());
            //Map myVar = new HashMap();

            JasperReport myReport=JasperCompileManager.compileReport("D://New Project/iReport/Data Pegawai Nip.jrxml");
            JasperPrint myPrint=JasperFillManager.fillReport(myReport,hm,con);
            JasperViewer.viewReport(myPrint,false);
            dispose();
        }
        catch(Exception e){}
    }//GEN-LAST:event_btnPrintSingleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrintPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnPrintAll;
    private javax.swing.JButton btnPrintSingle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrint;
    private javax.swing.JButton txtClear;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables

}
