/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OlahDatabase.java
 *
 * Created on Jul 18, 2011, 8:35:51 AM
 */

package overtimeapplication;

/**
 *
 * @author MuhLiX-Tech
 */
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;

public class FormJabatan extends javax.swing.JFrame {
    /** Creates new form OlahDatabase */
    public FormJabatan() {
        this.setLocation(300,225);
        initComponents();
        Baru();
        
    }
    private void Baru(){
        btnSave.setText("Save");
        txtKodeJab.requestFocus();
        txtKodeJab.setText("");
        txtNamaJab.setText("");

        try {
            Class.forName(KoneksiDatabase.driver);
            java.sql.Connection c = DriverManager.getConnection(KoneksiDatabase.database, KoneksiDatabase.user, KoneksiDatabase.pass);
            Statement s = c.createStatement();
            String sql = "select * from jabatan";
            ResultSet rs = s.executeQuery(sql);

            final String[] headers = {"Kode Jabatan", "Nama Jabatan"};
            rs.last();

            int n = rs.getRow();
            Object[][] data = new Object[n][2];
            int p = 0;
            rs.beforeFirst();
            while (rs.next()) {
                data[p][0] = rs.getString(1);
                data[p][1] = rs.getString(2);
                p++;
            }
            tblJabatan.setModel(new DefaultTableModel(data, headers));
            tblJabatan.setAlignmentX(CENTER_ALIGNMENT);
}
catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Koneksi, Ada Kesalahan.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void Simpan() {
        if (txtKodeJab.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Kode Jabatan !!!", "Peringatan", JOptionPane.ERROR_MESSAGE);
            txtKodeJab.requestFocus();
        } else if (txtNamaJab.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama Jabatan Harus Diisi !!!", "Peringatan", JOptionPane.ERROR_MESSAGE);
            txtNamaJab.requestFocus();
        } else {
            try {
                Class.forName(KoneksiDatabase.driver);
                java.sql.Connection c = DriverManager.getConnection(KoneksiDatabase.database, KoneksiDatabase.user, KoneksiDatabase.pass);
                Statement s = c.createStatement();
                String sql;

                if (btnSave.getText().equals("Save")) {
                    sql = "insert into jabatan values ('";
                    sql += txtKodeJab.getText() + "','";
                    sql += txtNamaJab.getText() + "')";
                    } else {
                    sql = "update jabatn set nama_dep = '";
                    sql += txtNamaJab.getText() + "'";
                    sql += "where kd_jab = '" + txtKodeJab.getText() + "'";
                }
                s.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Disimpan, Data Harus Lengkap !!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
            Baru();
        }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKodeJab = new javax.swing.JTextField();
        txtNamaJab = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJabatan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Jabatan");

        jLabel2.setText("Kode Jabatan");

        jLabel3.setText("Nama Jabatan");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        tblJabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJabatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJabatan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKodeJab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtNamaJab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeJab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaJab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel)
                    .addComponent(btnSave)
                    .addComponent(btnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        Baru();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
         if (txtKodeJab.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Kode Jabatan yang Akan dihapus dari Database!!!", "Peringatan", JOptionPane.ERROR_MESSAGE);
            txtKodeJab.requestFocus();
        }

else {
try {
            Class.forName(KoneksiDatabase.driver);
            java.sql.Connection c = DriverManager.getConnection(KoneksiDatabase.database, KoneksiDatabase.user, KoneksiDatabase.pass);
            Statement s = c.createStatement();
            String sql = "DELETE FROM jabatan where kd_jab ='"+txtKodeJab.getText()+"'";
            s.executeUpdate(sql);
            Baru();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kemungkinan terjadi kegagalan koneksi", "Warning", JOptionPane.ERROR_MESSAGE);
        }
}
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Simpan();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJabatanMouseClicked
        // TODO add your handling code here:

        btnSave.setText("Edit");
        txtKodeJab.setText(tblJabatan.getValueAt(tblJabatan.getSelectedRow(), 0).toString());
        txtNamaJab.setText(tblJabatan.getValueAt(tblJabatan.getSelectedRow(), 1).toString());

    }//GEN-LAST:event_tblJabatanMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormJabatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJabatan;
    private javax.swing.JTextField txtKodeJab;
    private javax.swing.JTextField txtNamaJab;
    // End of variables declaration//GEN-END:variables

}
