/*
 * formUtama.java
 *
 * Created on 11 july 2011, 9:55
 */

package overtimeapplication;

/**
 *
 * @author  MuhliX-Tech
 */
import javax.swing.*;

public class formUtama extends javax.swing.JFrame{
    
    /** Creates new form formUtama */
    public formUtama() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        tbPeg = new javax.swing.JButton();
        tbAbsensiLembur = new javax.swing.JButton();
        tbRekap = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tbLaporan = new javax.swing.JButton();
        deskPane = new javax.swing.JDesktopPane();
        imageLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemKeluar = new javax.swing.JMenuItem();
        mnuMaster = new javax.swing.JMenu();
        mnuPegawai = new javax.swing.JMenuItem();
        mnuGolongan = new javax.swing.JMenuItem();
        mnuDepartemen = new javax.swing.JMenuItem();
        mnuJabatan = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuInputAbsensi = new javax.swing.JMenuItem();
        mnuOlahAbsensi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuSettingAbsenLembur = new javax.swing.JMenuItem();
        mnuTarifLembur = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setRollover(true);

        tbPeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Medium 044.png"))); // NOI18N
        tbPeg.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tbPeg.setFocusable(false);
        tbPeg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbPeg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbPeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPegActionPerformed(evt);
            }
        });
        toolBar.add(tbPeg);

        tbAbsensiLembur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Medium 404.png"))); // NOI18N
        tbAbsensiLembur.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tbAbsensiLembur.setFocusable(false);
        tbAbsensiLembur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbAbsensiLembur.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbAbsensiLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAbsensiLemburActionPerformed(evt);
            }
        });
        toolBar.add(tbAbsensiLembur);

        tbRekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Medium 339.png"))); // NOI18N
        tbRekap.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tbRekap.setFocusable(false);
        tbRekap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbRekap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(tbRekap);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login Icon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(jButton1);

        tbLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Medium 253.png"))); // NOI18N
        tbLaporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tbLaporan.setFocusable(false);
        tbLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(tbLaporan);

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash.png"))); // NOI18N
        imageLabel.setBounds(100, 0, 808, 610);
        deskPane.add(imageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mnuFile.setText("File");

        mnuItemKeluar.setMnemonic('k');
        mnuItemKeluar.setText("Keluar");
        mnuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemKeluar);

        jMenuBar1.add(mnuFile);

        mnuMaster.setMnemonic('m');
        mnuMaster.setText("Master Data");

        mnuPegawai.setText("Pegawai");
        mnuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPegawaiActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuPegawai);

        mnuGolongan.setText("Golongan");
        mnuGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGolonganActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuGolongan);

        mnuDepartemen.setText("Departemen");
        mnuDepartemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDepartemenActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuDepartemen);

        mnuJabatan.setText("Jabatan");
        mnuJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJabatanActionPerformed(evt);
            }
        });
        mnuMaster.add(mnuJabatan);

        jMenuBar1.add(mnuMaster);

        mnuTransaksi.setText("Transaksi");

        mnuInputAbsensi.setText("Input Data Absensi");
        mnuInputAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInputAbsensiActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuInputAbsensi);

        mnuOlahAbsensi.setText("Olah Data Lembur");
        mnuOlahAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOlahAbsensiActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuOlahAbsensi);

        jMenuBar1.add(mnuTransaksi);

        jMenu1.setMnemonic('s');
        jMenu1.setText("Setting");

        mnuSettingAbsenLembur.setText("Waktu Absensi & Lembur");
        mnuSettingAbsenLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSettingAbsenLemburActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSettingAbsenLembur);

        mnuTarifLembur.setText("Jenis & Tarif Lembur");
        mnuTarifLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTarifLemburActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTarifLembur);

        jMenuBar1.add(jMenu1);

        mnuLaporan.setText("Laporan");

        jMenuItem3.setText("Data Pegawai");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuLaporan.add(jMenuItem3);

        jMenuItem2.setText("Lembur Pegawai");
        mnuLaporan.add(jMenuItem2);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKeluarActionPerformed
// TODO add your handling code here:
        int tutup = JOptionPane.showConfirmDialog(null, 
                "Apakah Anda Yakin ?","Exit",
                                            JOptionPane.YES_NO_OPTION);
        if(tutup==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mnuItemKeluarActionPerformed

    private void mnuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAboutMouseClicked

    private void mnuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPegawaiActionPerformed
        // TODO add your handling code here:
        deskPane.repaint();
        
        dataPegawai pegawai = new dataPegawai();
        deskPane.add(pegawai);
        pegawai.show();
        
    }//GEN-LAST:event_mnuPegawaiActionPerformed

    private void mnuGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGolonganActionPerformed
        // TODO add your handling code here:
        new FormGolongan().show();
    }//GEN-LAST:event_mnuGolonganActionPerformed

    private void mnuDepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDepartemenActionPerformed
        // TODO add your handling code here:
        new FormDepartemen().show();
    }//GEN-LAST:event_mnuDepartemenActionPerformed

    private void mnuJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJabatanActionPerformed
        // TODO add your handling code here:
        new FormJabatan().show();
    }//GEN-LAST:event_mnuJabatanActionPerformed

    private void mnuSettingAbsenLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSettingAbsenLemburActionPerformed
        // TODO add your handling code here:
        new settingLembur().show();
       

    }//GEN-LAST:event_mnuSettingAbsenLemburActionPerformed

    private void tbPegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPegActionPerformed
        // TODO add your handling code here:
         deskPane.repaint();

        dataPegawai pegawai = new dataPegawai();
        deskPane.add(pegawai);
        pegawai.show();
    }//GEN-LAST:event_tbPegActionPerformed

    private void tbAbsensiLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAbsensiLemburActionPerformed
        // TODO add your handling code here:
         deskPane.repaint();

        FormAbsensi absen = new FormAbsensi();
        deskPane.add(absen);
        absen.show();
    }//GEN-LAST:event_tbAbsensiLemburActionPerformed

    private void mnuInputAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInputAbsensiActionPerformed
        // TODO add your handling code here:
        deskPane.repaint();

        FormAbsensi absen = new FormAbsensi();
        deskPane.add(absen);
        absen.show();
    }//GEN-LAST:event_mnuInputAbsensiActionPerformed

    private void mnuOlahAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOlahAbsensiActionPerformed
        // TODO add your handling code here:
        deskPane.repaint();

        data_Lembur lem = new data_Lembur();
        deskPane.add(lem);
        lem.show();
    }//GEN-LAST:event_mnuOlahAbsensiActionPerformed

    private void mnuTarifLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTarifLemburActionPerformed
        // TODO add your handling code here:
        new tarifLembur().show();
    }//GEN-LAST:event_mnuTarifLemburActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new formPrintPegawai().show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuDepartemen;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuGolongan;
    private javax.swing.JMenuItem mnuInputAbsensi;
    private javax.swing.JMenuItem mnuItemKeluar;
    private javax.swing.JMenuItem mnuJabatan;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenu mnuMaster;
    private javax.swing.JMenuItem mnuOlahAbsensi;
    private javax.swing.JMenuItem mnuPegawai;
    private javax.swing.JMenuItem mnuSettingAbsenLembur;
    private javax.swing.JMenuItem mnuTarifLembur;
    private javax.swing.JMenu mnuTransaksi;
    private javax.swing.JButton tbAbsensiLembur;
    private javax.swing.JButton tbLaporan;
    private javax.swing.JButton tbPeg;
    private javax.swing.JButton tbRekap;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
    
}
